facebook_project/facebook_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_app/', include('login_app.urls')),
    path('main_app/', include('main_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facebook_project/login_app/urls.py
from django.urls import path 
from . import views

app_name = 'login_app'

urlpatterns = [
	path('login/', views.log_in, name='loginpage'),
	path('signup/', views.signup, name='signup'),
	path('logging_out/', views.logging_out, name='logging_out'),
]

facebook_project/main_app/urls.py
from django.urls import path 
from . import views

app_name = 'main_app'

urlpatterns = [
	path('home/', views.home, name='home'),
]

facebook_project/login_app/models.py
from django.db import models

# Create your models here.

facebook_project/main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	bio = models.CharField(max_length=400)
	profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
	follows = models.ManyToManyField('UserProfileInfo', related_name='followed_by', symmetrical=False, blank=True)

	def __str__(self):
		return (self.user.username +' '+ str(self.id))

facebook_project/login_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from main_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
	password = forms.CharField(widget= forms.PasswordInput)
	class Meta:
		model = User
		fields = ('username', 'email', 'password')


class LoginForm(forms.Form):
	username = forms.CharField(max_length=150)
	password = forms.CharField(widget=forms.PasswordInput())
	def clean(self):
		all_clean_data = super().clean()
		return all_clean_data

class UserProfileInfoForm(forms.ModelForm):
	class Meta:
		model = UserProfileInfo
		fields = ('bio', 'profile_pic')

facebook_project/login_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from . import forms
from main_app.views import home


# Create your views here.
def log_in(request):
	if request.user.is_authenticated:
		return redirect('/first_app/home/', permanent=False)
	errors = False
	if request.method == 'POST':
		login_form = forms.LoginForm(request.POST)
		if login_form.is_valid():
			clean_data = login_form.clean()
			user = authenticate(username=clean_data['username'], password=clean_data['password'])

			if user is not None:
				login(request, user)
				print('Logged In: {}'.format(user))
				return redirect('/main_app/home/', permanent=False)
				
			else:
				errors = True
	else:
		login_form = forms.LoginForm()

	return render(request, 'login_form.html', {
			'login_form': login_form,
			'errors': errors,})

def signup(request):
	if request.user.is_authenticated:
		return redirect('/first_app/home/', permanent=False)

	registered = False
	if request.method =='POST':
		user_form = forms.UserForm(data= request.POST) 
		profile_form = forms.UserProfileInfoForm(data= request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit= False)
			profile.user = user

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']
			
			profile.save()
			registered = True
			login(request, user)
			return redirect('/main_app/home/', permanent=False)



		else : 
			print(user_form.errors, profile_form.errors)

	else: 
		user_form = forms.UserForm()
		profile_form = forms.UserProfileInfoForm()

	return render(request, 'signup_form.html', context = {
		'user_form' : user_form,
		'profile_form' : profile_form, 
		'registered': registered
		})


@login_required
def logging_out(request):
	print(request.user)
	logout(request)
	print('logginngg ouutttttt........')
	return redirect('/login_app/login/')

facebook_project/main_app/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
	if request.user.is_authenticated:
		return render(request, 'home.html', {'logged_in': True, 'user': request.user})
	else:
		return render(request, 'home.html', {'logged_in': False})

facebook_project/login_app/templates/login_form.html
{% extends 'base.html' %}
{% block title %}Login Page{% endblock %}


{% block content%}

	{% if errors %}
		<p>The username and password are not matching Biatchhhh.</p>
	{% endif %}

	<h1>Fill the Login form</h1>
	<form enctype="multipart/form-data" method='POST'>
		{% csrf_token %}
		{{ login_form.as_p }}
		<input type="submit" value='signup'>

	</form>

	<p>Or <a href="{% url 'login_app:signup'%}">Create an Account</a></p>


{%endblock%}

facebook_project/login_app/templates/signup_form.html
{% extends "base.html" %}

{% block header_title %} Signup Form {% endblock %}

{% block content %}


{% if registered %}
	<h1> Thanks for registering! </h1>
{% else %}
	<h1> Fill the signup form : </h1>
	<form enctype="multipart/form-data" method="POST">
		{% csrf_token %}
		{{user_form.as_p}}
		{{profile_form.as_p}}
		<input type="submit" value="signup">
	</form>
{% endif %}

{% endblock %}

facebook_project/main_app/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
		<title>{%block title %}Title{% endblock %}</title>
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
		<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
		<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand " href="{% url 'main_app:home'%}" id="hive_logo_a">
			<img src="{% static 'images/hive_logo.png'%}" id="hive_logo">
		</a>
		
		<div class="collapse navbar-collapse">
			<ul class="navbar-nav mr-auto pl-5">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'main_app:home' %}">Home</a>
				</li>
				{% if logged_in %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							My Account
						</a>
					</li>
					
					<li class="nav-item">
				
					<div class = "bloc-user ">
					{% if not user.userprofileinfo.profile_pic %}

						<div class="button-signup inset">
							<img src="{% static 'images/no-picture.png' %}" >
						</div>
					{% else%}
						<a href="{% url 'main_app:home'%}">
						<div class="button-signup inset">
							<img src="{{user.userprofileinfo.profile_pic.url}}" >
						</div>
						</a>
					{% endif %}
					
					<div class="user-profile">
						<a href="{% url 'main_app:home'%}">
						<p>{{user.username}} </p>
						</a>
					</div>

					<div class="button-logout">
						<a href="{% url 'login_app:logging_out' %}" class="btn btn-danger btn-lg active " role="button" aria-pressed="true">Logout</a>
					</div>
				</div>
				</li>

				

				{% else %}
				
				<div class = "bloc-user ">
				
					<div class="button-login">
						<a href="{% url 'login_app:loginpage' %}" class="btn btn-danger btn-lg active " role="button" aria-pressed="true">Login</a>
					</div>
					<div class="button-signup">
						<a href="{% url 'login_app:signup' %}" class="btn btn-danger btn-lg active " role="button" aria-pressed="true">Sign up</a>
					</div>
				
				</div>
				
				{% endif %}	
			</ul>
		</div>
	</nav>  

	{% block content %}{% endblock %}



	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

facebook_project/main_app/templates/home.html
{% extends "base.html" %}

{% block header_title %} Home{% endblock %}

{% block content %}

{% if logged_in %}
<p>logged_in</p>
{% else %}
<p>not logged in</p>
{% endif %}

{% endblock %}